config/routes.rb
Graph::Application.routes.draw do
  resources :orgaos

  resources :parlamentares
  resources :grafos

end

app/models/membership.rb
class Membership
  include Mongoid::Document
  field :tipo, type: String
  belongs_to :orgao, inverse_of: :orgao
  belongs_to :parlamentar, inverse_of: :parlamentar
end

app/models/orgao.rb
class Orgao
  include Mongoid::Document
  field :id, type: String
  field :sigla, type: String
  field :descricao, type: String
  has_many :memberships


  validates_presence_of :sigla, :message => "Tem que ter uma sigla"

end

app/models/parlamentar.rb
class Parlamentar
  include Mongoid::Document
  field :idCcadastro, type: Integer
  field :matricula, type: Integer
  field :idParlamentar
  field :nome, type: String
  field :nomeParlamentar, type:String
  field :partido, type: String
  field :legislatura, type: String
  field :sexo, type: String
  field :uf, type: String
  field :gabinete, type: String
  field :anexo, type: String
  field :fone, type: String
  field :email, type: String
  has_many :memberships, :dependent => :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grafos_controller.rb
class GrafosController < ApplicationController
	def index
		@parlamentares = Parlamentar.all
	end
end

app/controllers/orgaos_controller.rb
class OrgaosController < ApplicationController
  # GET /orgaos
  # GET /orgaos.json
  def index
    @orgaos = Orgao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orgaos }
    end
  end

  # GET /orgaos/1
  # GET /orgaos/1.json
  def show
    @orgao = Orgao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orgao }
    end
  end

  # GET /orgaos/new
  # GET /orgaos/new.json
  def new
    @orgao = Orgao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orgao }
    end
  end

  # GET /orgaos/1/edit
  def edit
    @orgao = Orgao.find(params[:id])
  end

  # POST /orgaos
  # POST /orgaos.json
  def create
    @orgao = Orgao.new(params[:orgao])

    respond_to do |format|
      if @orgao.save
        format.html { redirect_to @orgao, notice: 'Orgao was successfully created.' }
        format.json { render json: @orgao, status: :created, location: @orgao }
      else
        format.html { render action: "new" }
        format.json { render json: @orgao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orgaos/1
  # PUT /orgaos/1.json
  def update
    @orgao = Orgao.find(params[:id])

    respond_to do |format|
      if @orgao.update_attributes(params[:orgao])
        format.html { redirect_to @orgao, notice: 'Orgao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orgao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgaos/1
  # DELETE /orgaos/1.json
  def destroy
    @orgao = Orgao.find(params[:id])
    @orgao.destroy

    respond_to do |format|
      format.html { redirect_to orgaos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/parlamentares_controller.rb
class ParlamentaresController < ApplicationController
  # GET /parlamentares
  # GET /parlamentares.json
  def index
    @parlamentares = Parlamentar.all

    @parlamentares = @parlamentares.where :partido => params[:partido] unless params[:partido]..nil?
    @parlamentares = @parlamentares.where :sexo => params[:sexo] unless params[:sexo].nil?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parlamentares }
    end
  end

  # GET /parlamentares/1
  # GET /parlamentares/1.json
  def show
    @parlamentar = Parlamentar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parlamentar }
    end
  end

  # GET /parlamentares/new
  # GET /parlamentares/new.json
  def new
    @parlamentar = Parlamentar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parlamentar }
    end
  end

  # GET /parlamentares/1/edit
  def edit
    @parlamentar = Parlamentar.find(params[:id])
  end

  # POST /parlamentares
  # POST /parlamentares.json
  def create
    @parlamentar = Parlamentar.new(params[:parlamentar])

    respond_to do |format|
      if @parlamentar.save
        format.html { redirect_to @parlamentar, notice: 'Parlamentar was successfully created.' }
        format.json { render json: @parlamentar, status: :created, location: @parlamentar }
      else
        format.html { render action: "new" }
        format.json { render json: @parlamentar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parlamentares/1
  # PUT /parlamentares/1.json
  def update
    @parlamentar = Parlamentar.find(params[:id])

    respond_to do |format|
      if @parlamentar.update_attributes(params[:parlamentar])
        format.html { redirect_to @parlamentar, notice: 'Parlamentar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parlamentar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parlamentares/1
  # DELETE /parlamentares/1.json
  def destroy
    @parlamentar = Parlamentar.find(params[:id])
    @parlamentar.destroy

    respond_to do |format|
      format.html { redirect_to parlamentares_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grafos_helper.rb
module GrafosHelper
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/helpers/orgoes_helper.rb
module OrgoesHelper
end

app/helpers/parlamentares_helper.rb
module ParlamentaresHelper
end

app/helpers/parlamentars_helper.rb
module ParlamentarsHelper
end

app/views/grafos/index.haml
-#encoding: utf-8
%h1 Parlamentares e comissões
- @parlamentares.each do |dep|
	%ul
		%li
			%h3=dep.nome
			%p=dep.partido
			%p=dep.email
		%ul
			.titular
				Titular
				-dep.memberships.where(:tipo => "titular").each do |com|
					%li
						=com.orgao.sigla unless com.orgao.nil?
						%small= com.orgao.descricao unless com.orgao.nil?
				.titular
					Suplente

				-dep.memberships.where(:tipo => "suplente").each do |com|
					%li
						=com.orgao.sigla unless com.orgao.nil?
						%small= com.orgao.descricao unless com.orgao.nil?
			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graph</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orgaos/_form.html.haml
= form_for @orgao do |f|
  - if @orgao.errors.any?
    #error_explanation
      %h2= "#{pluralize(@orgao.errors.count, "error")} prohibited this orgao from being saved:"
      %ul
        - @orgao.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :id
    = f.text_field :id
  .field
    = f.label :sigla
    = f.text_field :sigla
  .field
    = f.label :descricao
    = f.text_field :descricao
  .actions
    = f.submit 'Save'

app/views/orgaos/edit.html.haml
%h1 Editing orgao

= render 'form'

= link_to 'Show', @orgao
\|
= link_to 'Back', orgaos_path

app/views/orgaos/index.html.haml
%h1 Listing orgaos

%table
  %tr
    %th Id
    %th Sigla
    %th Descricao
    %th
    %th
    %th

  - @orgaos.each do |orgao|
    %tr
      %td= orgao.id
      %td= orgao.sigla
      %td= orgao.descricao
      %td= link_to 'Show', orgao
      %td= link_to 'Edit', edit_orgao_path(orgao)
      %td= link_to 'Destroy', orgao, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Orgao', new_orgao_path

app/views/orgaos/new.html.haml
%h1 New orgao

= render 'form'

= link_to 'Back', orgaos_path

app/views/orgaos/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @orgao.id
%p
  %b Sigla:
  = @orgao.sigla
%p
  %b Descricao:
  = @orgao.descricao

= link_to 'Edit', edit_orgao_path(@orgao)
\|
= link_to 'Back', orgaos_path

app/views/parlamentares/_form.html.haml
= form_for @parlamentar do |f|
  - if @parlamentar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@parlamentar.errors.count, "error")} prohibited this parlamentar from being saved:"
      %ul
        - @parlamentar.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :partido
    = f.text_field :partido
  .field
    = f.label :legislatura
    = f.text_field :legislatura
  .actions
    = f.submit 'Save', :class => :button

app/views/parlamentares/edit.html.haml
%h1 Editing parlamentar

= render 'form'

= link_to 'Show', @parlamentar
\|
= link_to 'Back', parlamentares_path

app/views/parlamentares/index.html.haml
%h1 Listing parlamentares

%table
  %tr
    %th Nome
    %th Partido
    %th Legislatura
    %th
    %th
    %th

  - @parlamentares.each do |parlamentar|
    %tr
      %td= parlamentar.nome
      %td= parlamentar.partido
      %td= parlamentar.legislatura
      %td= link_to 'Show', parlamentar
      %td= link_to 'Edit', edit_parlamentar_path(parlamentar)
      %td= link_to 'Destroy', parlamentar, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Parlamentar', new_parlamentar_path

app/views/parlamentares/new.html.haml
%h1 New parlamentar

= render 'form'

= link_to 'Back', parlamentares_path

app/views/parlamentares/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @parlamentar.nome
%p
  %b Partido:
  = @parlamentar.partido
%p
  %b Legislatura:
  = @parlamentar.legislatura

= link_to 'Edit', edit_parlamentar_path(@parlamentar)
\|
= link_to 'Back', parlamentares_path